# Generated by Django 3.0.12 on 2021-03-09 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='localhost', max_length=128, verbose_name='hostname')),
                ('status', models.CharField(default='free', max_length=16, verbose_name='Status')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Auto Renew')),
                ('last_interaction', models.DateTimeField(null=True, verbose_name='Last Interaction')),
                ('reserved_token', models.CharField(max_length=64, null=True)),
                ('reserved_until', models.DateTimeField(null=True, verbose_name='Reserved Until')),
                ('reserved_for_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_saasinstance_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instance',
            },
        ),
    ]
