# Generated by Django 4.0 on 2022-03-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saascontract',
            name='account_iban',
            field=models.CharField(default='', max_length=64, verbose_name='Account IBAN'),
        ),
        migrations.AddField(
            model_name='saascontract',
            name='account_owner',
            field=models.CharField(default='', max_length=200, verbose_name='Account Owner'),
        ),
        migrations.AddField(
            model_name='saascontract',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='confirmed'),
        ),
        migrations.AddField(
            model_name='saascontract',
            name='payment_method',
            field=models.CharField(default='SEPA_TRANSFER', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='saascontract',
            name='sepa_mandate',
            field=models.CharField(default='', max_length=64, verbose_name='SEPA Mandate'),
        ),
        migrations.AddField(
            model_name='saascontract',
            name='sepa_mandate_date',
            field=models.DateField(null=True, verbose_name='Date of SEPA Mandate'),
        ),
        migrations.DeleteModel(
            name='SaasProductLanguage',
        ),
    ]
