# Generated by Django 3.1.7 on 2021-03-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='name')),
                ('periodLengthInMonths', models.IntegerField(verbose_name='length')),
                ('currencyCode', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('costPerPeriod', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cost')),
                ('noticePeriodTypeInDays', models.IntegerField(verbose_name='notice')),
            ],
            options={
                'db_table': 'plan',
            },
        ),
    ]
