# Generated by Django 3.2.1 on 2021-05-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter', models.BooleanField(default=True, verbose_name='newsletter')),
                ('newsletter_subscribed_on', models.DateTimeField(null=True, verbose_name='newsletter_subscribed_on')),
                ('newsletter_cancelled', models.DateTimeField(null=True, verbose_name='newsletter_cancelled')),
                ('language_code', models.CharField(max_length=16, verbose_name='language_code')),
                ('verified', models.BooleanField(default=True, verbose_name='verified')),
                ('verification_token', models.CharField(max_length=64, verbose_name='verification_token')),
                ('verification_until', models.DateTimeField(null=True, verbose_name='verification_until')),
                ('organisation_name', models.CharField(max_length=64, verbose_name='organisation_name')),
                ('person_name', models.CharField(max_length=64, verbose_name='person_name')),
                ('street', models.CharField(max_length=64, verbose_name='street')),
                ('number', models.CharField(max_length=11, verbose_name='number')),
                ('post_code', models.CharField(max_length=10, verbose_name='post_code')),
                ('city', models.CharField(max_length=16, verbose_name='city')),
                ('country_code', models.CharField(max_length=16, verbose_name='country_code')),
                ('email_address', models.EmailField(max_length=254, verbose_name='email_address')),
                ('is_active', models.BooleanField(default=True, verbose_name='ist_active')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='SaasPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='name')),
                ('periodLengthInMonths', models.IntegerField(verbose_name='length')),
                ('currencyCode', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('costPerPeriod', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cost')),
                ('noticePeriodTypeInDays', models.IntegerField(verbose_name='notice')),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='SaasContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='end_date')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='auto_renew')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='core_saascontact_list', to='core.saascustomer')),
                ('instance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='core_saascontact_list', to='core.saasinstance')),
                ('plan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='core_saascontact_list', to='core.saasplan')),
            ],
            options={
                'db_table': 'SaasContact',
            },
        ),
    ]
