# Generated by Django 4.0 on 2022-03-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasproduct',
            name='deactivation_url',
            field=models.CharField(default='https://%prefix%identifier.example.org/deactivate', max_length=250, verbose_name='Deativation URL'),
        ),
        migrations.AlterField(
            model_name='saascontract',
            name='account_iban',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='Account IBAN'),
        ),
        migrations.AlterField(
            model_name='saascontract',
            name='account_owner',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Account Owner'),
        ),
        migrations.AlterField(
            model_name='saascontract',
            name='sepa_mandate',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='SEPA Mandate'),
        ),
    ]
