# Generated by Django 4.0 on 2022-03-17 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_saascontract_account_iban_saascontract_account_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saascontract',
            name='instance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_list', to='core.saasinstance'),
        ),
    ]
