# Generated by Django 4.0 on 2022-03-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_saasproduct_deactivation_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saasproduct',
            name='activation_url',
            field=models.CharField(default='', max_length=250, verbose_name='Activation URL'),
        ),
        migrations.AlterField(
            model_name='saasproduct',
            name='deactivation_url',
            field=models.CharField(default='', max_length=250, verbose_name='Deactivation URL'),
        ),
        migrations.AlterField(
            model_name='saasproduct',
            name='instance_password_reset_url',
            field=models.CharField(default='/reset_password', max_length=250, verbose_name='Password Reset URL'),
        ),
    ]
