# Generated by Django 3.2.3 on 2021-05-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210522_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasinstance',
            name='initial_password',
            field=models.CharField(default='topsecret', max_length=64, verbose_name='Initial Password'),
        ),
    ]
