# Generated by Django 4.0 on 2022-04-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_saasproduct_activation_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saasproduct',
            name='instance_url',
            field=models.CharField(default='https://#Prefix#Identifier.example.org', max_length=250, verbose_name='Instance URL'),
        ),
    ]
