# Generated by Django 3.2.3 on 2021-06-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210525_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasinstance',
            name='port',
            field=models.IntegerField(default=-1, verbose_name='port'),
        ),
    ]
