# Generated by Django 4.0 on 2022-04-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_saasproduct_instance_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasplan',
            name='period_length_in_days',
            field=models.IntegerField(default=0, verbose_name='Period Length in Days'),
        ),
        migrations.AlterField(
            model_name='saasplan',
            name='period_length_in_months',
            field=models.IntegerField(default=0, verbose_name='Period Length in Months'),
        ),
    ]
