# Generated by Django 3.2.5 on 2021-07-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_saasinstance_port'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='saascontract',
            table='saas_contract',
        ),
        migrations.AlterModelTable(
            name='saascustomer',
            table='saas_customer',
        ),
        migrations.AlterModelTable(
            name='saasinstance',
            table='saas_instance',
        ),
        migrations.AlterModelTable(
            name='saasplan',
            table='saas_plan',
        ),
    ]
