# Generated by Django 4.0 on 2022-04-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_saasplan_period_length_in_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasinstance',
            name='password1',
            field=models.CharField(default='topsecret', max_length=64, verbose_name='Password1'),
        ),
        migrations.AddField(
            model_name='saasinstance',
            name='password2',
            field=models.CharField(default='topsecret', max_length=64, verbose_name='Password2'),
        ),
    ]
