# Generated by Django 3.2.9 on 2021-11-16 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20210706_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='saascustomer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saasinstance',
            name='status',
            field=models.CharField(default='in_preparation', max_length=16, verbose_name='Status'),
        ),
    ]
