# Generated by Django 4.0 on 2022-04-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_saasinstance_password1_saasinstance_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='saasplan',
            name='quota_app',
            field=models.CharField(default='500M', max_length=20, verbose_name='Quota for Application'),
        ),
        migrations.AddField(
            model_name='saasplan',
            name='quota_storage',
            field=models.CharField(default='0M', max_length=20, verbose_name='Quota for Storage'),
        ),
    ]
