# Generated by Django 3.2.9 on 2021-11-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211116_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saascustomer',
            name='person_name',
        ),
        migrations.AddField(
            model_name='saascustomer',
            name='first_name',
            field=models.CharField(max_length=64, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='saascustomer',
            name='last_name',
            field=models.CharField(max_length=64, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='saascustomer',
            name='city',
            field=models.CharField(max_length=16, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='saascustomer',
            name='country_code',
            field=models.CharField(default='DE', max_length=16, verbose_name='country_code'),
        ),
        migrations.AlterField(
            model_name='saascustomer',
            name='language_code',
            field=models.CharField(default='de', max_length=16, verbose_name='language_code'),
        ),
        migrations.AlterField(
            model_name='saascustomer',
            name='number',
            field=models.CharField(max_length=11, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='saascustomer',
            name='organisation_name',
            field=models.CharField(max_length=64, null=True, verbose_name='organisation_name'),
        ),
        migrations.AlterField(
            model_name='saascustomer',
            name='post_code',
            field=models.CharField(max_length=10, null=True, verbose_name='post_code'),
        ),
        migrations.AlterField(
            model_name='saascustomer',
            name='street',
            field=models.CharField(max_length=64, null=True, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='saascustomer',
            name='verification_token',
            field=models.CharField(max_length=64, null=True, verbose_name='verification_token'),
        ),
    ]
