# Generated by Django 4.0 on 2022-04-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_saasplan_is_active_saasplan_quota_app_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saasplan',
            name='is_active',
        ),
        migrations.AddField(
            model_name='saasplan',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='is public'),
        ),
    ]
