# Generated by Django 4.0 on 2022-04-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_saasplan_is_active_saasplan_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saasproduct',
            name='instance_url',
            field=models.CharField(default='https://#Prefix#Identifier.example.org/', max_length=250, verbose_name='Instance URL'),
        ),
    ]
