# Generated by Django 4.0 on 2022-04-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_saasproduct_instance_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasplan',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Sorting Order'),
        ),
    ]
