# Generated by Django 4.0.4 on 2022-04-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_saasplan_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasproduct',
            name='description',
            field=models.CharField(default='', max_length=250, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='saasproduct',
            name='description_de',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='saasproduct',
            name='description_en',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Description'),
        ),
    ]
