# Generated by Django 3.2.9 on 2021-11-30 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_saasplan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='name')),
                ('activationurl', models.CharField(max_length=200, verbose_name='activationurl')),
            ],
        ),
        migrations.CreateModel(
            name='SaasProductLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='DE', max_length=10, verbose_name='language')),
                ('payment_details', models.CharField(default='', max_length=300, verbose_name='payment_details')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='core_saasproductlanguage_list', to='core.saasproduct')),
            ],
        ),
    ]
