# Generated by Django 4.0.4 on 2022-05-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_saasconfiguration_name_de_saasconfiguration_name_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saasconfiguration',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='saasconfiguration',
            name='name_en',
        ),
    ]
