# Generated by Django 4.0.4 on 2022-05-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_saasconfiguration_name_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasproduct',
            name='login_url',
            field=models.CharField(default='', max_length=250, verbose_name='Login_URL'),
        ),
    ]
