# Generated by Django 4.0.4 on 2022-05-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_saasconfiguration_name_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasinstance',
            name='django_secret_key',
            field=models.CharField(default='topsecret', max_length=64, verbose_name='Django Secret Key'),
        ),
    ]
