# Generated by Django 4.0 on 2022-03-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_saasinstance_db_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasproduct',
            name='slug',
            field=models.CharField(default='invalid', unique=True, max_length=50, verbose_name='slug'),
        ),
    ]
