# Generated by Django 4.0.4 on 2022-05-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_saasinstance_django_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saasconfiguration',
            name='value',
            field=models.CharField(max_length=5000, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='saasconfiguration',
            name='value_de',
            field=models.CharField(max_length=5000, null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='saasconfiguration',
            name='value_en',
            field=models.CharField(max_length=5000, null=True, verbose_name='value'),
        ),
    ]
