# Generated by Django 4.0.4 on 2022-05-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_saasinstance_django_secret_key'),
        ('core', '0017_saasproduct_login_url'),
    ]

    operations = [
    ]
