# Generated by Django 4.0.4 on 2022-06-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_saasconfiguration_value_and_more'),
        ('core', '0018_merge_20220525_0936'),
    ]

    operations = [
    ]
