# Generated by Django 4.0 on 2022-03-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_saasinstance_identifier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saasplan',
            old_name='noticePeriodTypeInDays',
            new_name='noticePeriodInDays',
        ),
    ]
