# Generated by Django 4.0.4 on 2022-06-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20220525_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasinstance',
            name='custom_domain',
            field=models.CharField(default='', max_length=250, verbose_name='Custom Domain'),
        ),
    ]
