# Generated by Django 4.0 on 2022-03-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_noticeperiodtypeindays_saasplan_noticeperiodindays'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasproduct',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='saascustomer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
