# Generated by Django 4.0.4 on 2022-06-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20220604_2011'),
        ('core', '0019_saasinstance_custom_domain'),
    ]

    operations = [
    ]
