# Generated by Django 4.0.5 on 2022-06-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20220607_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasinstance',
            name='additional_storage',
            field=models.IntegerField(default=0, verbose_name='Additional Storage'),
        ),
        migrations.AddField(
            model_name='saasplan',
            name='additional_storage_size',
            field=models.CharField(default='', max_length=10, verbose_name='Additional Storage Size'),
        ),
        migrations.AddField(
            model_name='saasplan',
            name='cost_for_storage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost for Storage'),
        ),
    ]
