# Generated by Django 4.0 on 2022-03-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_saasproduct_is_active_alter_saascustomer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasinstance',
            name='channel',
            field=models.CharField(default='stable', max_length=128, verbose_name='channel'),
        ),
    ]
