# Generated by Django 4.0.5 on 2022-06-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_historicalsaasplan_historicalsaasinstance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaasplan',
            name='descr_1_de',
            field=models.CharField(default='TODO', max_length=200, null=True, verbose_name='Description 1'),
        ),
        migrations.AddField(
            model_name='historicalsaasplan',
            name='descr_1_en',
            field=models.CharField(default='TODO', max_length=200, null=True, verbose_name='Description 1'),
        ),
        migrations.AddField(
            model_name='historicalsaasplan',
            name='descr_2_de',
            field=models.CharField(default='TODO', max_length=200, null=True, verbose_name='Description 2'),
        ),
        migrations.AddField(
            model_name='historicalsaasplan',
            name='descr_2_en',
            field=models.CharField(default='TODO', max_length=200, null=True, verbose_name='Description 2'),
        ),
        migrations.AddField(
            model_name='historicalsaasplan',
            name='descr_3_de',
            field=models.CharField(default='TODO', max_length=200, null=True, verbose_name='Description 3'),
        ),
        migrations.AddField(
            model_name='historicalsaasplan',
            name='descr_3_en',
            field=models.CharField(default='TODO', max_length=200, null=True, verbose_name='Description 3'),
        ),
        migrations.AddField(
            model_name='historicalsaasplan',
            name='descr_4_de',
            field=models.CharField(default='TODO', max_length=200, null=True, verbose_name='Description 4'),
        ),
        migrations.AddField(
            model_name='historicalsaasplan',
            name='descr_4_en',
            field=models.CharField(default='TODO', max_length=200, null=True, verbose_name='Description 4'),
        ),
        migrations.AddField(
            model_name='historicalsaasplan',
            name='descr_caption_de',
            field=models.CharField(default='TODO', max_length=200, null=True, verbose_name='Description Caption'),
        ),
        migrations.AddField(
            model_name='historicalsaasplan',
            name='descr_caption_en',
            field=models.CharField(default='TODO', max_length=200, null=True, verbose_name='Description Caption'),
        ),
        migrations.AddField(
            model_name='historicalsaasplan',
            name='descr_target_de',
            field=models.CharField(default='TODO', max_length=200, null=True, verbose_name='Description Target'),
        ),
        migrations.AddField(
            model_name='historicalsaasplan',
            name='descr_target_en',
            field=models.CharField(default='TODO', max_length=200, null=True, verbose_name='Description Target'),
        ),
        migrations.AddField(
            model_name='historicalsaasplan',
            name='name_de',
            field=models.CharField(max_length=16, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='historicalsaasplan',
            name='name_en',
            field=models.CharField(max_length=16, null=True, verbose_name='name'),
        ),
    ]
