# Generated by Django 4.0 on 2022-03-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_saasinstance_hostname and port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('language', models.CharField(max_length=10, verbose_name='language')),
                ('value', models.CharField(max_length=250, verbose_name='value')),
            ],
            options={
                'db_table': 'saas_configuration',
            },
        ),
        migrations.AddField(
            model_name='saasinstance',
            name='activation_token',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='saasinstance',
            name='pacuser',
            field=models.CharField(default='xyz00', max_length=128, verbose_name='pacuser'),
        ),
        migrations.AlterField(
            model_name='saasproduct',
            name='activationurl',
            field=models.CharField(max_length=250, verbose_name='activationurl'),
        ),
    ]
