# Generated by Django 4.0 on 2022-03-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_saasconfiguration_saasinstance_activation_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saasproduct',
            name='activationurl',
        ),
        migrations.AddField(
            model_name='saasproduct',
            name='activation_url',
            field=models.CharField(default='https://%prefix%identifier.example.org/activate', max_length=250, verbose_name='Activation URL'),
        ),
        migrations.AddField(
            model_name='saasproduct',
            name='instance_url',
            field=models.CharField(default='https://%prefix%identifier.example.org', max_length=250, verbose_name='Instance URL'),
        ),
        migrations.AlterField(
            model_name='saasproduct',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
    ]
