# Generated by Django 4.0 on 2022-03-11 05:37

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_saasproduct_activationurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saascustomer',
            name='number',
        ),
        migrations.AlterField(
            model_name='saascustomer',
            name='city',
            field=models.CharField(default='', max_length=16, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='saascustomer',
            name='country_code',
            field=django_countries.fields.CountryField(default='DE', max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='saascustomer',
            name='first_name',
            field=models.CharField(default='', max_length=64, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='saascustomer',
            name='last_name',
            field=models.CharField(default='', max_length=64, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='saascustomer',
            name='post_code',
            field=models.CharField(default='', max_length=10, verbose_name='post_code'),
        ),
        migrations.AlterField(
            model_name='saascustomer',
            name='street',
            field=models.CharField(default='', max_length=64, verbose_name='street'),
        ),
    ]
