# Generated by Django 4.0.6 on 2022-08-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_historicalsaasinstance_custom_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsaasinstance',
            name='custom_domain',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Custom Domain'),
        ),
        migrations.AlterField(
            model_name='historicalsaasinstance',
            name='dbms_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL/MariaDB')], default='mysql', max_length=64, verbose_name='Database Type'),
        ),
        migrations.AlterField(
            model_name='saasinstance',
            name='custom_domain',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Custom Domain'),
        ),
        migrations.AlterField(
            model_name='saasinstance',
            name='dbms_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL/MariaDB')], default='mysql', max_length=64, verbose_name='Database Type'),
        ),
        migrations.AlterField(
            model_name='saasproduct',
            name='dbms_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL/MariaDB')], default='mysql', max_length=64, verbose_name='Database Type'),
        ),
    ]
