# Generated by Django 4.0 on 2022-03-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_saascustomer_number_alter_saascustomer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saascustomer',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Mr Dr', 'Mr Dr'), ('Mrs Dr', 'Mrs Dr')], max_length=64, verbose_name='Title'),
        ),
    ]
