# Generated by Django 4.0 on 2022-03-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_saascustomer_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saasinstance',
            name='auto_renew',
        ),
        migrations.AddField(
            model_name='saascontract',
            name='latest_cancel_date',
            field=models.DateTimeField(null=True, verbose_name='latest_cancel_date'),
        ),
    ]
