# Generated by Django 4.0.6 on 2022-09-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_historicalsaasinstance_custom_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasproduct',
            name='first_page_logo',
            field=models.ImageField(null=True, upload_to='product_logos', verbose_name='First Page Logo'),
        ),
        migrations.AddField(
            model_name='saasproduct',
            name='first_page_purpose',
            field=models.CharField(default='', max_length=1500, verbose_name='First Page Purpose'),
        ),
    ]
