# Generated by Django 4.0 on 2022-03-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_saasinstance_auto_renew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saascontract',
            name='end_date',
            field=models.DateField(null=True, verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='saascontract',
            name='latest_cancel_date',
            field=models.DateField(null=True, verbose_name='latest_cancel_date'),
        ),
        migrations.AlterField(
            model_name='saascontract',
            name='start_date',
            field=models.DateField(null=True, verbose_name='start_date'),
        ),
    ]
