# Generated by Django 4.1.1 on 2022-10-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_saasproduct_first_page_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasproduct',
            name='first_page_purpose_de',
            field=models.CharField(default='', max_length=1500, null=True, verbose_name='First Page Purpose'),
        ),
        migrations.AddField(
            model_name='saasproduct',
            name='first_page_purpose_en',
            field=models.CharField(default='', max_length=1500, null=True, verbose_name='First Page Purpose'),
        ),
    ]
