# Generated by Django 4.1.1 on 2022-10-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_saasproduct_first_page_purpose_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saasproduct',
            name='login_url',
            field=models.CharField(default='/', max_length=250, verbose_name='Login_URL'),
        ),
    ]
